//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_receiveable
    {
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string Ref { get; set; }
        public Nullable<double> Debit { get; set; }
        public string Credit { get; set; }
        public double Balance { get; set; }
    }
}
