//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Cash___
    {
        public System.DateTime DATE { get; set; }
        public string Description { get; set; }
        public string Ref { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit_ { get; set; }
        public double Balance_ { get; set; }
    }
}
