//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_daily___
    {
        public string Date_ { get; set; }
        public double Sale_of__Gasol95 { get; set; }
        public Nullable<double> Sale_of_disel_ { get; set; }
        public Nullable<double> total_sale_ { get; set; }
        public double gasol_95_of_good_sold_ { get; set; }
        public Nullable<double> disel_cost__of_good_sold { get; set; }
        public double total_COGS { get; set; }
        public Nullable<double> gross_profit_ { get; set; }
        public Nullable<double> sale_offcie_staff_salary { get; set; }
        public Nullable<double> gate_controller_salary { get; set; }
        public Nullable<double> utility_expense_ { get; set; }
        public Nullable<double> depresisation_ { get; set; }
        public double net_income { get; set; }
    }
}
