//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Sale_Office__
    {
        public string PONumber { get; set; }
        public string TIME_IN { get; set; }
        public string TIME_OUT { get; set; }
        public string TOTAL_TIME { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string OrderName { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<double> OrderID { get; set; }
    }
}
