//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_stock_disel__
    {
        public double SAFETY_STOCK { get; set; }
        public double Begiining_stock_ { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string PO_NUMBER { get; set; }
        public string PARTOL_TYPE { get; set; }
        public Nullable<double> Amount_sold_ { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<double> Balance_before_order_ { get; set; }
        public Nullable<double> No_of_time_to_purchase_ { get; set; }
        public Nullable<double> Amount_purchase_ { get; set; }
        public Nullable<double> Ending_stock__litre_ { get; set; }
        public Nullable<double> Amount1 { get; set; }
    }
}
