//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_stock___
    {
        public double safety { get; set; }
        public Nullable<double> F2 { get; set; }
        public double Beginning_Stock_litre_ { get; set; }
        public Nullable<double> F4 { get; set; }
        public double Beginning_Stock_Baht_ { get; set; }
        public Nullable<double> F6 { get; set; }
        public Nullable<double> Amount_Sold__Day_litre_ { get; set; }
        public Nullable<double> F8 { get; set; }
        public Nullable<double> Amount_Sold__Day_Baht_ { get; set; }
        public Nullable<double> F10 { get; set; }
        public Nullable<double> Balance_before_order { get; set; }
        public Nullable<double> F12 { get; set; }
        public Nullable<double> No__of_time_to_purchase { get; set; }
        public Nullable<double> F14 { get; set; }
        public Nullable<double> Amount_Perchased_litre_ { get; set; }
        public Nullable<double> F16 { get; set; }
        public Nullable<double> Amount_Perchased_baht_ { get; set; }
        public Nullable<double> F18 { get; set; }
        public double Balance_litre_ { get; set; }
        public Nullable<double> F20 { get; set; }
        public double Balance_Baht_ { get; set; }
        public Nullable<double> F22 { get; set; }
        public Nullable<double> F23 { get; set; }
        public Nullable<double> F24 { get; set; }
        public Nullable<double> F25 { get; set; }
        public Nullable<double> F26 { get; set; }
    }
}
