//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_
    {
        public double CompanyID { get; set; }
        public Nullable<double> UserID { get; set; }
        public string Companyname { get; set; }
        public Nullable<double> shipping_Address { get; set; }
    }
}
