//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_
    {
        public double Beginning_Stock_litre_ { get; set; }
        public Nullable<double> F2 { get; set; }
        public Nullable<double> Amount_Perchased_litre_ { get; set; }
        public Nullable<double> F4 { get; set; }
        public double Amount_Sold__Day_litre_ { get; set; }
        public Nullable<double> F6 { get; set; }
        public Nullable<double> Ending__Stock_litre_ { get; set; }
        public Nullable<double> F8 { get; set; }
    }
}
