//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Capstone2Entities17 : DbContext
    {
        public Capstone2Entities17()
            : base("name=Capstone2Entities17")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Account_payable__> C_Account_payable__ { get; set; }
        public virtual DbSet<Account_receiveable> Account_receiveables { get; set; }
        public virtual DbSet<C_Cash___> C_Cash___ { get; set; }
        public virtual DbSet<Company_> Company_ { get; set; }
        public virtual DbSet<C_daily___> C_daily___ { get; set; }
        public virtual DbSet<daily_> daily_ { get; set; }
        public virtual DbSet<Driver_> Driver_ { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Manager_> Manager_ { get; set; }
        public virtual DbSet<monthly_> monthly_ { get; set; }
        public virtual DbSet<Order_> Order_ { get; set; }
        public virtual DbSet<Purchase_order> Purchase_orders { get; set; }
        public virtual DbSet<Reconciliation_> Reconciliation_ { get; set; }
        public virtual DbSet<C_Sale_Office__> C_Sale_Office__ { get; set; }
        public virtual DbSet<C_stock___> C_stock___ { get; set; }
        public virtual DbSet<C_stock_disel__> C_stock_disel__ { get; set; }
        public virtual DbSet<STOCK_> STOCK_ { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Truck_> Truck_ { get; set; }
        public virtual DbSet<User_> User_ { get; set; }
    }
}
