//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_
    {
        public Nullable<double> PaymentNO { get; set; }
        public string OrderName { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> shipping_Address { get; set; }
        public Nullable<double> ShippingID { get; set; }
        public string PONumber { get; set; }
        public Nullable<double> OrderID { get; set; }
        public string VEHICLE_NUMBER { get; set; }
    }
}
