//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_order
    {
        public string PO_NUMBER { get; set; }
        public Nullable<double> PaymentNO { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string PARTOL_TYPE { get; set; }
        public Nullable<double> O_ty { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<double> Price_Liter { get; set; }
        public Nullable<double> shipping_Address { get; set; }
        public Nullable<double> CompanyID { get; set; }
        public string Companyname { get; set; }
        public Nullable<double> TaxNumber { get; set; }
        public string F12 { get; set; }
        public string F13 { get; set; }
        public string F14 { get; set; }
    }
}
