//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reconciliation_
    {
        public System.DateTime DATE { get; set; }
        public string PO_NUMBER { get; set; }
        public Nullable<double> PAYMENT_NUMBER { get; set; }
        public Nullable<double> INVOICE_NUMBER { get; set; }
        public Nullable<double> SHIPMENT_NUMBER { get; set; }
        public string TRUCK_NUMBER { get; set; }
        public string PARTOL_TYPE { get; set; }
        public Nullable<double> O_ty__Liter_ { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public string AGENT { get; set; }
    }
}
