//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_
    {
        public double SAFETY_STOCK { get; set; }
        public double Beginning_stock { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string PO_NUMBER { get; set; }
        public string PARTOL_TYPE { get; set; }
        public Nullable<double> Amount_sold__litre_ { get; set; }
        public Nullable<double> AMOUNT_baht_ { get; set; }
        public Nullable<double> BALANCE_BEFORE_ORDER { get; set; }
        public Nullable<double> No_of_time_to_purchase_ { get; set; }
        public Nullable<double> AMOUNT_PURCHASE__LITRE_ { get; set; }
        public Nullable<double> Amount_purchase__baht_ { get; set; }
        public Nullable<double> Ending_stock__litre_ { get; set; }
    }
}
