//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck_
    {
        public double TruckID { get; set; }
        public Nullable<double> DriverID { get; set; }
        public string VEHICLE_NUMBER { get; set; }
        public string DriverName { get; set; }
    }
}
