//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBACKEND.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_
    {
        public double UserID { get; set; }
        public string UserName_By_Email { get; set; }
        public string NameUser { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<double> Age { get; set; }
        public string Gender { get; set; }
    }
}
